POST http://localhost:4000/app/signup
Content-Type: : application/json

{
    "email": "testing@gmail.com",
    "password": "test123",
    "books": [{
        "bookName": "The Silence of the Lambs",
        "page": 1
    }]
}